pool:
  vmImage: 'ubuntu-latest'

steps:
- task: ShellScript@2.206.0
  displayName: Parse version from Dockerfile
  inputs:
    scriptPath: version.sh

- task: CmdLine@2.201.1
  displayName: Docker build
  inputs:
    script: docker build -t kotatsuclub/ghost:$(docker_tag) .

- script: |
    curl -LO https://storage.googleapis.com/container-structure-test/v1.11.0/container-structure-test-linux-amd64 && mv container-structure-test-linux-amd64 container-structure-test && chmod +x container-structure-test && sudo mv container-structure-test /usr/local/bin/
  displayName: "Install container-structure-test"

- script: |
    container-structure-test test --image kotatsuclub/ghost:$(docker_tag) --config container-structure-tests.yaml
  displayName: "Test built container image"

- task: Docker@2.201.0
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Docker push
  inputs:
    containerRegistry: dockerhub
    command: push
    repository: kotatsuclub/ghost
    tags: $(docker_tag)

- task: GitHubRelease@1.201.0
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Create GitHub release
  inputs:
    gitHubConnection: kotatsuclub
    repositoryName: $(Build.Repository.Name)
    tag: $(docker_tag)
    tagSource: manual
    title: $(docker_tag)
    releaseNotesSource: input
    releaseNotes: "docker image: `kotatsuclub/ghost:$(docker_tag)`"
